In [ ]:
import numpy as np

In [ ]:
list(),tuple(),set(),dict()

([], (), set(), {})

In [ ]:
x=[1,3,5,"data engineering"]

In [ ]:
x

[1, 3, 5, 'data engineering']

In [ ]:
type(x[0]),type(x[1]),type(x[2]),type(x[3])

(int, int, int, str)

In [ ]:
for i in range(1,10):
  print(np.random.randint(0,10))

4
4
0
6
1
4
6
2
6


In [ ]:
data=np.random.randint(0,10,(6,6))

In [ ]:
data

array([[4, 4, 5, 7, 8, 0],
       [0, 7, 8, 1, 5, 4],
       [0, 5, 0, 3, 4, 9],
       [2, 0, 2, 2, 9, 8],
       [5, 9, 5, 2, 4, 8],
       [7, 0, 2, 4, 4, 4]])

In [ ]:
data[0:3,5:]

array([[0],
       [4],
       [9]])

In [ ]:
data

array([[4, 4, 5, 7, 8, 0],
       [0, 7, 8, 1, 5, 4],
       [0, 5, 0, 3, 4, 9],
       [2, 0, 2, 2, 9, 8],
       [5, 9, 5, 2, 4, 8],
       [7, 0, 2, 4, 4, 4]])

In [ ]:
data[-6:4,-6:4]

array([[4, 4, 5, 7],
       [0, 7, 8, 1],
       [0, 5, 0, 3],
       [2, 0, 2, 2]])

In [ ]:
data[-3:3,-3:3]

array([], shape=(0, 0), dtype=int64)

In [ ]:
data=np.random.randint(0,100,(6,6))

In [ ]:
data

array([[ 1, 74, 49,  1, 54,  0],
       [45, 12, 86, 37, 52, 26],
       [50, 25, 57, 71,  1, 54],
       [85, 32, 92, 38, 12, 43],
       [68, 44, 71, 81, 99, 49],
       [90, 79, 39, 18, 36, 22]])

In [ ]:
data[-6:-4,-6:-4]

array([[ 1, 74],
       [45, 12]])

In [ ]:
data[3:6,2:4]

array([[92, 38],
       [71, 81],
       [39, 18]])

In [ ]:
data[-3:-1,-3:-1]

array([[38, 12],
       [81, 99]])

In [ ]:
data

array([[ 1, 74, 49,  1, 54,  0],
       [45, 12, 86, 37, 52, 26],
       [50, 25, 57, 71,  1, 54],
       [85, 32, 92, 38, 12, 43],
       [68, 44, 71, 81, 99, 49],
       [90, 79, 39, 18, 36, 22]])

In [ ]:
data.shape

(6, 6)

In [ ]:
data.size

36

In [ ]:
data.T

array([[ 1, 45, 50, 85, 68, 90],
       [74, 12, 25, 32, 44, 79],
       [49, 86, 57, 92, 71, 39],
       [ 1, 37, 71, 38, 81, 18],
       [54, 52,  1, 12, 99, 36],
       [ 0, 26, 54, 43, 49, 22]])

In [ ]:
data**2

array([[   1, 5476, 2401,    1, 2916,    0],
       [2025,  144, 7396, 1369, 2704,  676],
       [2500,  625, 3249, 5041,    1, 2916],
       [7225, 1024, 8464, 1444,  144, 1849],
       [4624, 1936, 5041, 6561, 9801, 2401],
       [8100, 6241, 1521,  324, 1296,  484]])

In [ ]:
data/2

array([[ 0.5, 37. , 24.5,  0.5, 27. ,  0. ],
       [22.5,  6. , 43. , 18.5, 26. , 13. ],
       [25. , 12.5, 28.5, 35.5,  0.5, 27. ],
       [42.5, 16. , 46. , 19. ,  6. , 21.5],
       [34. , 22. , 35.5, 40.5, 49.5, 24.5],
       [45. , 39.5, 19.5,  9. , 18. , 11. ]])

In [ ]:
data//2

array([[ 0, 37, 24,  0, 27,  0],
       [22,  6, 43, 18, 26, 13],
       [25, 12, 28, 35,  0, 27],
       [42, 16, 46, 19,  6, 21],
       [34, 22, 35, 40, 49, 24],
       [45, 39, 19,  9, 18, 11]])

In [ ]:
data*2

array([[  2, 148,  98,   2, 108,   0],
       [ 90,  24, 172,  74, 104,  52],
       [100,  50, 114, 142,   2, 108],
       [170,  64, 184,  76,  24,  86],
       [136,  88, 142, 162, 198,  98],
       [180, 158,  78,  36,  72,  44]])

In [ ]:
import numpy as np

In [ ]:
data=np.random.randint(1,0,(4,5))

ValueError: low >= high