In [ ]:
import numpy as np

In [ ]:
data=np.random.randint(0,10,(5,3))

In [ ]:
data

array([[8, 7, 6],
       [7, 7, 4],
       [0, 5, 7],
       [7, 8, 6],
       [0, 1, 4]])

In [ ]:
data.max(axis=0)

array([8, 8, 7])

In [ ]:
data

array([[8, 7, 6],
       [7, 7, 4],
       [0, 5, 7],
       [7, 8, 6],
       [0, 1, 4]])

In [ ]:
data.max(axis=1)

array([8, 7, 7, 8, 4])

In [ ]:
data.min(axis=0)

array([0, 1, 4])

In [ ]:
data.min(axis=1)

array([6, 4, 0, 6, 0])

In [ ]:
data.sum(axis=0)

array([22, 28, 27])

In [ ]:
data.sum(axis=1)

array([21, 18, 12, 21,  5])

In [ ]:
data.max()

np.int64(8)

In [ ]:
data.min()

np.int64(0)

In [ ]:
data.argmax(axis=1)

array([0, 0, 2, 1, 2])

In [ ]:
data

array([[8, 7, 6],
       [7, 7, 4],
       [0, 5, 7],
       [7, 8, 6],
       [0, 1, 4]])

In [ ]:
data.argmin(axis=0)

array([2, 4, 1])

In [ ]:
data.argmin(axis=1)

array([2, 2, 0, 2, 0])

In [ ]:
data.sum(axis=0)

array([22, 28, 27])

In [ ]:
data.sum(axis=0).max()

np.int64(28)

In [ ]:
data.sum(axis=1).max()

np.int64(21)

In [ ]:
data.sum(axis=0).max()-data.sum(axis=1).max()

np.int64(7)

In [ ]:
3data.sum()

np.int64(77)