In [ ]:
import numpy as np

In [ ]:
list(),str(),tuple(),set(),dict()

([], '', (), set(), {})

In [ ]:
y=np.array([1,2,3])

In [ ]:
x=[1,2,3]

In [ ]:
type(x),type(y)

(list, numpy.ndarray)

In [ ]:
x/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [ ]:
y/2

array([0.5, 1. , 1.5])

In [ ]:
x=[1,2,3,"data science"]

In [ ]:
x

[1, 2, 3, 'data science']

In [ ]:
type(x[0]),type(x[1]),type(x[2]),type(x[3])

(int, int, int, str)

In [ ]:
y=np.array([1,2,3,3.6,"data"])

In [ ]:
type(y[0]),type(y[1]),type(y[2]),type(y[3])

(numpy.str_, numpy.str_, numpy.str_, numpy.str_)

In [ ]:
y

array(['1', '2', '3', '3.6', 'data'], dtype='<U32')

In [ ]:
for i in range(1,10):
  print(np.random.randint(0,10))

4
9
3
9
0
7
5
5
4


In [ ]:
np.random.randint(0,10,(5,5))

array([[7, 6, 8, 7, 9],
       [0, 5, 9, 5, 0],
       [1, 0, 7, 2, 1],
       [7, 7, 6, 5, 7],
       [1, 1, 9, 2, 7]])

In [ ]:
data=np.random.randint(0,100,(5,5))

In [ ]:
data

array([[84, 48, 28, 65, 10],
       [60, 93, 72, 65, 62],
       [83, 92, 37, 83, 84],
       [19, 49, 64, 70, 74],
       [ 7, 82, 52, 50, 35]])

In [ ]:
data[0:3,4:5]

array([[10],
       [62],
       [84]])

In [ ]:
data[-5:-4,-5:-4]

array([[84]])

In [ ]:
data[-4:-2,-3:-2]

array([[72],
       [37]])

In [ ]:
data[-3:-1,-3:-1]

array([[37, 83],
       [64, 70]])

In [ ]:
data[0,:]

array([84, 48, 28, 65, 10])

In [ ]:
data[,:0]

array([84, 60, 83, 19,  7])

In [ ]:
data.shape

(5, 5)

In [ ]:
data.size

25

In [ ]:
data.T

array([[84, 60, 83, 19,  7],
       [48, 93, 92, 49, 82],
       [28, 72, 37, 64, 52],
       [65, 65, 83, 70, 50],
       [10, 62, 84, 74, 35]])

In [ ]:
data

array([[84, 48, 28, 65, 10],
       [60, 93, 72, 65, 62],
       [83, 92, 37, 83, 84],
       [19, 49, 64, 70, 74],
       [ 7, 82, 52, 50, 35]])

In [ ]:
data

array([[84, 48, 28, 65, 10],
       [60, 93, 72, 65, 62],
       [83, 92, 37, 83, 84],
       [19, 49, 64, 70, 74],
       [ 7, 82, 52, 50, 35]])

In [ ]:
x=2

In [ ]:
data**2

array([[7056, 2304,  784, 4225,  100],
       [3600, 8649, 5184, 4225, 3844],
       [6889, 8464, 1369, 6889, 7056],
       [ 361, 2401, 4096, 4900, 5476],
       [  49, 6724, 2704, 2500, 1225]])

In [ ]:
x=np.random.randint(0,10,(3,3))
y=np.random.randint(0,10,(3,3))

In [ ]:
x

array([[1, 0, 7],
       [9, 8, 7],
       [0, 5, 1]])

In [ ]:
y

array([[2, 8, 2],
       [5, 3, 5],
       [1, 3, 7]])

In [ ]:
np.add(x,2)

array([[ 3,  2,  9],
       [11, 10,  9],
       [ 2,  7,  3]])

In [ ]:
np.multiply(x,2)

array([[ 2,  0, 14],
       [18, 16, 14],
       [ 0, 10,  2]])

In [ ]:
np.divide(x,2)

array([[0.5, 0. , 3.5],
       [4.5, 4. , 3.5],
       [0. , 2.5, 0.5]])

In [ ]:
np.floor_divide(x,2)

array([[0, 0, 3],
       [4, 4, 3],
       [0, 2, 0]])

In [ ]:
np.exp(x)

array([[2.71828183e+00, 1.00000000e+00, 1.09663316e+03],
       [8.10308393e+03, 2.98095799e+03, 1.09663316e+03],
       [1.00000000e+00, 1.48413159e+02, 2.71828183e+00]])

In [ ]:
np.pow(x,2)

array([[ 1,  0, 49],
       [81, 64, 49],
       [ 0, 25,  1]])

In [ ]:
np.random.rand(5,5)

array([[0.48981424, 0.80487072, 0.81120293, 0.83530402, 0.99717038],
       [0.07099539, 0.57504013, 0.37381179, 0.37157955, 0.76890344],
       [0.41029796, 0.68286066, 0.77460625, 0.04738481, 0.91155312],
       [0.8930638 , 0.84593858, 0.01741577, 0.37801979, 0.29164885],
       [0.71614137, 0.76889902, 0.72632107, 0.67067581, 0.71294204]])

In [ ]:
np.random.randn(1300,1300).std()

np.float64(1.0002335644471163)

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
data=np.random.randint(0,10,(5,5))

In [ ]:
data

array([[3, 6, 5, 6, 1],
       [4, 0, 3, 1, 4],
       [0, 2, 5, 7, 3],
       [2, 7, 8, 7, 0],
       [9, 6, 7, 5, 6]])

In [ ]:
print(data.sum())
print(data.min())
print(data.max())

107
0
9


In [ ]:
data.argmax()

np.int64(20)

In [ ]:
data=np.random.randint(0,10,(3,3))

In [ ]:
data

array([[6, 1, 3],
       [3, 6, 7],
       [0, 8, 2]])

In [ ]:
data.sum(axis=1)

array([10, 16, 10])

In [ ]:
data.sum(axis=0)

array([ 9, 15, 12])

In [ ]:
data

array([[6, 1, 3],
       [3, 6, 7],
       [0, 8, 2]])

In [ ]:
data.argmin(axis=1)

array([1, 0, 0])

In [ ]:
data.max(axis=0)

array([6, 8, 7])