In [ ]:
import numpy as np

In [ ]:
data=np.random.randint(0,10,(3,3))

In [ ]:
data

array([[6, 6, 6],
       [8, 4, 3],
       [4, 7, 7]])

In [ ]:
data.sum()

np.int64(51)

In [ ]:
data.sum(axis=1)

array([18, 15, 18])

In [ ]:
data.sum(axis=0)

array([18, 17, 16])

In [ ]:
data.max()

np.int64(8)

In [ ]:
data

array([[6, 6, 6],
       [8, 4, 3],
       [4, 7, 7]])

In [ ]:
data.max(axis=1)

array([6, 8, 7])

In [ ]:
data.argmax(axis=1)

array([0, 0, 1])

In [ ]:
data=np.random.randint(0,100,(10,5))

In [ ]:
data  ### 10 stores, total 5 products sales

array([[55, 99, 55,  2, 78],
       [10, 20, 22, 25, 67],
       [97, 99, 27, 56, 60],
       [55, 20, 57, 95, 89],
       [59, 11, 59, 20, 67],
       [38, 90, 31, 25, 11],
       [46, 45, 96, 93, 66],
       [37, 64, 48, 71, 85],
       [95, 98,  1,  7, 15],
       [73, 90, 24,  4, 65]])

In [ ]:
data.sum(axis=1)

array([289, 144, 339, 316, 216, 195, 346, 305, 216, 256])

In [ ]:
data.sum(axis=1).argmin()+1

np.int64(2)

In [ ]:
data.sum(axis=1)

array([289, 144, 339, 316, 216, 195, 346, 305, 216, 256])

In [ ]:
data.sum(axis=0)

array([565, 636, 420, 398, 603])

In [ ]:
data.sum()

np.int64(2622)

In [ ]:
data=np.random.randint(10,100,(10,5))

In [ ]:
data.sum(axis=0).argmax()+1

np.int64(3)

In [ ]:
data.sum(axis=0)

array([647, 620, 673, 559, 459])

In [ ]:
data.sum(axis=0)[3:].sum()

np.int64(1018)

In [ ]:
data[:,3:5].sum()

np.int64(1018)

In [ ]:
data

array([[96, 34, 74, 78, 99],
       [69, 71, 77, 58, 60],
       [80, 53, 77, 50, 46],
       [75, 62, 66, 36, 28],
       [24, 81, 29, 55, 52],
       [95, 93, 39, 62, 11],
       [66, 47, 99, 71, 71],
       [63, 33, 51, 34, 16],
       [42, 63, 80, 63, 58],
       [37, 83, 81, 52, 18]])

In [ ]:
data

array([[96, 34, 74, 78, 99],
       [69, 71, 77, 58, 60],
       [80, 53, 77, 50, 46],
       [75, 62, 66, 36, 28],
       [24, 81, 29, 55, 52],
       [95, 93, 39, 62, 11],
       [66, 47, 99, 71, 71],
       [63, 33, 51, 34, 16],
       [42, 63, 80, 63, 58],
       [37, 83, 81, 52, 18]])

In [ ]:
data.sum(axis=0).max()

np.int64(673)

In [ ]:
data.sum(axis=0).min()

np.int64(459)

In [ ]:
data.sum(axis=0).max()-data.sum(axis=0).min()

np.int64(214)

In [ ]:
data=np.random.randint(0,10,10)

In [ ]:
data.mean()

np.float64(4.3)

In [ ]:
data

array([7, 6, 4, 2, 6, 8, 1, 0, 4, 5])

In [ ]:
np.median(data)

np.float64(4.5)

In [ ]:
data

array([7, 6, 4, 2, 6, 8, 1, 0, 4, 5])

In [ ]:
np.quantile(data,0.25)

np.float64(2.5)

In [ ]:
np.quantile(data,0.75)

np.float64(6.0)

In [ ]:
np.quantile(data,0.50)

np.float64(4.5)

In [ ]:
np.median(data)

np.float64(4.5)

In [ ]:
### Descriptive Statistics
mean
median
max
min
range
q1
q3
iqr
std
var

NameError: name 'mean' is not defined

In [ ]:
np.std(data)

np.float64(2.4919871588754225)

In [ ]:
np.var(data)

np.float64(6.21)

In [ ]:
####

In [ ]:
data=np.random.randint(0,10,(10,2))

In [ ]:
np.corrcoef(data.T)

array([[ 1.        , -0.06489604],
       [-0.06489604,  1.        ]])

In [ ]:
v1=np.arange(1,11)

In [ ]:
v2=np.arange(10,20)

In [ ]:
v1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
x=[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
x.reverse()
v2=np.array(x)
v2

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [ ]:
data[:,0]=v1
data[:,1]=v2

In [ ]:
np.corrcoef(data.T)

array([[ 1., -1.],
       [-1.,  1.]])

In [ ]:
    c1  c2
c1  1   -1
c2  -1     1

In [ ]:
data=np.random.randint(0,10,(5,5))

In [ ]:
np.corrcoef(data)

array([[ 1.        ,  0.27183014, -0.9927901 ,  0.69883104,  0.94394736],
       [ 0.27183014,  1.        , -0.372678  ,  0.70974034,  0.33648869],
       [-0.9927901 , -0.372678  ,  1.        , -0.77588018, -0.96308682],
       [ 0.69883104,  0.70974034, -0.77588018,  1.        ,  0.85338202],
       [ 0.94394736,  0.33648869, -0.96308682,  0.85338202,  1.        ]])